apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: consul
  namespace: default
spec:
  type: state.consul
  version: v1
  metadata:
  - name: datacenter
    value: dc1 # Required. Example: dc1
  - name: httpAddr
    value: $consulAddress